### ISSUE TITLE
您好，我在运行项目的时候报了错，希望能帮我看看，谢谢

### ISSUE THREAD

**Issue by LuJenning** [lxhAndSmh/HyperLPR#2]
编译器报错  Cause: executing external native build for cmake 后面说是CMakeLists.txt的问题，但是我不知道哪里有错

**Comment by lxhAndSmh** [comment]
找到你的 AndroidStudio SDK 目录下 的 cmake 文件夹，删除，然后更改你的 NDK 的版本，建议使用 r14b,重新编译试试。
![image](https://user-images.githubusercontent.com/23186482/63680311-edc58200-c825-11e9-8b52-17062c007bc6.png)

**Comment by LuJenning** [comment]
谢谢啊 我自己解决了
